import type { Chapter } from "./types";

// Allah is never depicted; He is conveyed through light, sky, and creation. Pages name canon
// entities in `cast` and describe only the scene/action — appearance comes from the canon.
// Quotes are tagged by English chapter name and must be verified against an authentic translation.

const chapter: Chapter = {
  id: "who-is-allah",
  title: "Who Is Allah?",
  subtitle: "The one God who made everything and loves you",
  palette:
    "warm dawn light — soft gold, cream, dusty rose and gentle sky-blue by day, deepening to " +
    "indigo and silver starlight by night; everything opening toward light",
  pages: [
    // ───────────────────────── COVER ─────────────────────────
    {
      type: "cover",
      text: "Who Is Allah?",
      cast: ["mountains", "sea-shore"],
      scene:
        "Title cover: dawn breaking over a vast peaceful world — great mountains on one side, a calm " +
        "sea on the other, the sky moving from deep blue to warm gold, one bright morning star. " +
        "Render the title \"Who Is Allah?\" in an elegant cream serif across the upper third.",
    },

    // ───────────────────────── PART ONE ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part One", title: "Before Anything Began" },
      theme: "light",
      cast: ["cosmos"],
      scene: "The vast quiet cosmos before the world existed, soft galaxies in endless gentle dark.",
    },
    {
      type: "narrative",
      text: "This whole book is about Allah. \u201cAllah\u201d is simply the name of God. The two words mean the same thing.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "An immense calm night sky full of soft stars over still dunes.",
    },
    {
      type: "narrative",
      text: "Long before the earth, the sea, or the very first morning, there was Allah. He has no beginning.",
      pos: "bottom",
      theme: "light",
      cast: ["cosmos"],
      scene: "Deep cosmos with the faintest first warm light glowing far off in the dark.",
    },
    {
      type: "narrative",
      text: "Nothing made Allah, and nothing is older than Him. He has always been, and He always will be.",
      pos: "top",
      theme: "dark",
      cast: ["cosmos"],
      scene: "Soft luminous galaxies drifting in endless space, a pale calm glow in the upper sky.",
    },
    {
      type: "narrative",
      text: "Everything else \u2014 every star, every sea, every living thing \u2014 was made by Him.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "Countless stars arching over quiet dunes, the whole sky alive with gentle light.",
    },
    {
      type: "arabic",
      arabic: { word: "\u062E\u064E\u0627\u0644\u0650\u0642", translit: "Khaliq", meaning: "The Maker \u2014 the One who creates everything out of nothing." },
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A gentle radiant glow rising LOW over a calm dark horizon; the center stays calm and dark.",
    },
    {
      type: "narrative",
      text: "To make something, Allah does not need tools or time. He simply says to it, \u201cBe,\u201d and it is.",
      pos: "bottom",
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A soft ribbon of golden light unfurling from a starry heaven toward dark land below.",
    },
    {
      type: "quote",
      quote: {
        translation: "When He decrees a thing, He only says to it, \u201cBe,\u201d and it is.",
        source: "Ya-Sin \u00b7 Qur\u2019an 36:82",
      },
      theme: "light",
      pos: "center",
      cast: ["light-of-revelation"],
      scene: "A luminous column of light meeting the horizon, a feeling of quiet, effortless power; calm darkened center.",
    },

    // ───────────────────────── PART TWO ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Two", title: "There Is Only One God" },
      theme: "light",
      cast: ["night-sky"],
      scene: "A single very bright star alone in a vast indigo sky over still dunes.",
    },
    {
      type: "narrative",
      text: "There is only one God. Not many gods \u2014 only one. He has no partner and no equal.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "One radiant star far brighter than all the rest, alone over the quiet desert.",
    },
    {
      type: "narrative",
      text: "Allah was not born, and He has no mother, father, or children. Nothing is like Him in any way.",
      pos: "top",
      theme: "dark",
      cast: ["cosmos"],
      scene: "Vast serene galaxies; a calm pale region of sky at the top.",
    },
    {
      type: "narrative",
      text: "He has no body and no shape. Our eyes cannot see Him, the way they can see the sun.",
      pos: "bottom",
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "Pure radiant light too bright to look at directly, glowing softly above dark hills.",
    },
    {
      type: "narrative",
      text: "Yet He sees everything, and nothing is hidden from Him \u2014 not even a quiet thought inside you.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "A boundless starry sky watching gently over a tiny sleeping town far below.",
    },
    {
      type: "arabic",
      arabic: { word: "\u0627\u0644\u0644\u0647", translit: "Allah", meaning: "The one God \u2014 the Maker of all things. \u201cAllah\u201d and \u201cGod\u201d mean the same." },
      theme: "light",
      cast: [],
      scene: "A warm radiant glow rising LOW over a calm desert horizon at dusk; the center stays calm and dark.",
    },
    {
      type: "narrative",
      text: "Allah gave people a book of His own words, to tell them the truth about Him. It is called the Qur\u2019an.",
      pos: "bottom",
      theme: "light",
      cast: ["reed-pen"],
      scene: "A reed pen resting beside an open, blank sheet of parchment in warm lamplight.",
    },
    {
      type: "narrative",
      text: "In it, Allah taught a short, beautiful chapter that tells us exactly who He is.",
      pos: "top",
      theme: "dark",
      cast: ["light-of-revelation"],
      scene: "Soft light spilling gently downward from above; a pale calm sky at the top.",
    },
    {
      type: "quote",
      quote: {
        translation:
          "Say, \u201cHe is Allah, who is One. Allah, the Eternal. He neither gives birth nor was born, and there is none equal to Him.\u201d",
        source: "Sincerity \u00b7 Qur\u2019an 112:1-4",
      },
      theme: "light",
      pos: "center",
      cast: ["light-of-revelation"],
      scene: "A single pure source of light at the heart of a calm dark sky, radiating softly outward.",
    },

    // ───────────────────────── PART THREE ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Three", title: "Signs All Around You" },
      theme: "light",
      cast: ["arabian-desert"],
      scene: "A vast desert valley at golden hour, open and full of gentle light.",
    },
    {
      type: "narrative",
      text: "We cannot see Allah with our eyes. But everywhere we look, He has left signs that He is real.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert"],
      scene: "A wide sunlit desert stretching to far mountains, warm and open.",
    },
    {
      type: "narrative",
      text: "A sign is something that points to something else \u2014 the way footprints point to the one who walked.",
      pos: "top",
      theme: "dark",
      cast: ["arabian-desert"],
      scene: "A single line of footprints crossing soft sand toward a bright horizon; pale sky above.",
    },
    {
      type: "narrative",
      text: "Look up by day: the sun rises right on time, warms your face, and sets \u2014 every single day.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert"],
      scene: "A glowing sunrise spilling golden light across the dunes and distant hills.",
    },
    {
      type: "narrative",
      text: "Look up by night: countless stars, and a moon that grows and fades in a steady, faithful rhythm.",
      pos: "bottom",
      theme: "light",
      cast: ["crescent-moon"],
      scene: "A slender crescent moon glowing among soft stars in a deep indigo dusk sky.",
    },
    {
      type: "narrative",
      text: "See the mountains, standing firm and still, holding the earth steady beneath your feet.",
      pos: "top",
      theme: "dark",
      cast: ["mountains"],
      scene: "Great mountains rising into soft haze, immense and calm; pale bright sky at the top.",
    },
    {
      type: "narrative",
      text: "See the wide sea, brimming with water and life, never once spilling past its shore.",
      pos: "bottom",
      theme: "light",
      cast: ["sea-shore"],
      scene: "A calm sea meeting the shore at dawn, gentle waves, a glowing path of light on the water.",
    },
    {
      type: "narrative",
      text: "Allah sends the rain from the sky, and the dry, brown land wakes up soft and green and alive.",
      pos: "bottom",
      theme: "light",
      cast: ["rain-and-greenery"],
      scene: "Gentle rain falling on dry earth that is turning green with fresh shoots and small flowers.",
    },
    {
      type: "quote",
      quote: {
        translation: "...and We made every living thing from water. Will they not then believe?",
        source: "The Prophets \u00b7 Qur\u2019an 21:30",
      },
      theme: "light",
      pos: "center",
      cast: ["rain-and-greenery"],
      scene: "Rain glistening on new green life under breaking light; a calm darkened band across the middle.",
    },
    {
      type: "narrative",
      text: "From one tiny seed He grows a great tree, with cool shade for birds and sweet fruit for you.",
      pos: "bottom",
      theme: "light",
      cast: ["great-tree"],
      scene: "A single majestic tree with wide leafy branches on gentle ground, warm light through the leaves.",
    },
    {
      type: "narrative",
      text: "He fills the sky with birds and the fields with animals, and He feeds and cares for every one.",
      pos: "top",
      theme: "dark",
      cast: ["flock-of-birds"],
      scene: "A graceful flock of birds wheeling across a bright golden sky; pale open sky at the top.",
    },
    {
      type: "narrative",
      text: "And He made you \u2014 your eyes, your breath, and the small, steady heart beating in your chest right now.",
      pos: "bottom",
      theme: "light",
      cast: ["mother-and-child"],
      scene: "A mother softly cradling her baby in warm gentle light, partly turned away, tender and quiet.",
    },
    {
      type: "narrative",
      text: "None of this made itself. Each thing is a gift \u2014 and every gift points back to the Giver.",
      pos: "bottom",
      theme: "light",
      cast: ["oasis"],
      scene: "A green oasis with a clear pool, palms and small birds, glowing in soft golden light.",
    },
    {
      type: "quote",
      quote: {
        translation: "So which of the favors of your Lord would you deny?",
        source: "The Most Merciful \u00b7 Qur\u2019an 55:13",
      },
      theme: "light",
      pos: "center",
      cast: ["oasis"],
      scene: "Sunlight pouring over a lush oasis full of life; a calm darkened center band.",
    },

    // ───────────────────────── PART FOUR ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Four", title: "What Allah Is Like" },
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A warm field of radiant light glowing softly over a calm horizon.",
    },
    {
      type: "narrative",
      text: "Allah has many beautiful names. Each one is a little window that shows us something true about Him.",
      pos: "bottom",
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "Gentle beams of golden light fanning out across a soft dawn sky.",
    },
    {
      type: "narrative",
      text: "He is the Most Merciful. Mercy means gentle, loving care \u2014 even more than a mother gives her child.",
      pos: "bottom",
      theme: "light",
      cast: ["mother-and-child"],
      scene: "A mother tenderly sheltering her baby in soft warm light, partly turned away.",
    },
    {
      type: "arabic",
      arabic: { word: "\u0631\u064E\u062D\u0652\u0645\u064E\u0629", translit: "Rahma", meaning: "Mercy \u2014 Allah\u2019s endless love, gentleness, and care for you." },
      theme: "light",
      cast: [],
      scene: "A soft warm rose-gold glow gathering low over a calm horizon; the center stays calm and dark.",
    },
    {
      type: "narrative",
      text: "He is the Most Forgiving. When we do wrong and feel sorry, He loves to forgive us and start again.",
      pos: "top",
      theme: "dark",
      cast: ["light-of-revelation"],
      scene: "Warm light breaking softly through parting clouds; a pale calm sky at the top.",
    },
    {
      type: "narrative",
      text: "He is the Provider. The food you eat and the warm home you sleep in are all gifts from Him.",
      pos: "bottom",
      theme: "light",
      cast: ["dates-and-bread"],
      scene: "A woven basket of dates and round flatbread in warm inviting light.",
    },
    {
      type: "narrative",
      text: "He is the All-Knowing. He knows everything that was, everything that is, and all that is still to come.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "An immense star-filled sky, vast and all-seeing, over a tiny quiet world below.",
    },
    {
      type: "narrative",
      text: "He is the Most Wise and the Most Fair. He never wrongs anyone, not even by the weight of a seed.",
      pos: "top",
      theme: "dark",
      cast: ["scales"],
      scene: "A pair of bronze balance scales resting perfectly level in warm light; pale calm space at the top.",
    },
    {
      type: "quote",
      quote: {
        translation:
          "In the name of Allah, the Most Gracious, the Most Merciful. All praise is for Allah, Lord of all the worlds.",
        source: "The Opening \u00b7 Qur\u2019an 1:1-2",
        arabic: "\u0628\u0650\u0633\u0652\u0645\u0650 \u0627\u0644\u0644\u0647\u0650 \u0627\u0644\u0631\u0651\u064E\u062D\u0652\u0645\u064E\u0670\u0646\u0650 \u0627\u0644\u0631\u0651\u064E\u062D\u0650\u064A\u0645\u0650",
      },
      theme: "light",
      pos: "center",
      cast: ["light-of-revelation"],
      scene: "A luminous, welcoming sky opening over a calm horizon; a gently darkened center for text.",
    },

    // ───────────────────────── PART FIVE ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Five", title: "Closer Than You Think" },
      theme: "light",
      cast: ["night-sky"],
      scene: "A warm star-filled night sky leaning gently over a small sleeping town.",
    },
    {
      type: "narrative",
      text: "Allah is not far away and out of reach. He is closer to you than you can even imagine.",
      pos: "bottom",
      theme: "light",
      cast: ["lantern-home"],
      scene: "A small home with a warm lantern glowing in its window under a vast dusk sky.",
    },
    {
      type: "narrative",
      text: "He hears you even when you whisper \u2014 even when you only speak quietly inside your own heart.",
      pos: "bottom",
      theme: "light",
      cast: ["lantern-home"],
      scene: "A single warm-lit window glowing in the gentle blue dusk, intimate and safe.",
    },
    {
      type: "narrative",
      text: "You do not need a special place or special words. You can call on Him anywhere, at any time.",
      pos: "top",
      theme: "dark",
      cast: ["arabian-desert"],
      scene: "A lone open desert under a wide soft sky, peaceful and unhurried; pale bright sky at the top.",
    },
    {
      type: "narrative",
      text: "He never grows tired of listening, and He is never, ever too busy for you.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "An endless tender night sky cradling the quiet earth below.",
    },
    {
      type: "quote",
      quote: {
        translation:
          "And when My servants ask you about Me \u2014 indeed I am near. I respond to the call of the one who calls upon Me.",
        source: "The Cow \u00b7 Qur\u2019an 2:186",
      },
      theme: "light",
      pos: "center",
      cast: ["light-of-revelation"],
      scene: "Soft light reaching gently down toward the earth like an answer; a calm darkened center.",
    },
    {
      type: "narrative",
      text: "Talking to Allah is called prayer. It can be as simple as \u201cO Allah, help me,\u201d or just \u201cthank You.\u201d",
      pos: "bottom",
      theme: "light",
      cast: ["lantern-home"],
      scene: "A pair of small open hands cupped softly in the warm lantern light, seen from above so no face shows.",
    },
    {
      type: "arabic",
      arabic: { word: "\u062F\u064F\u0639\u064E\u0627\u0621", translit: "Du\u2019a", meaning: "A call to God \u2014 talking to Allah and asking Him for what you need." },
      theme: "light",
      cast: ["oil-lamp"],
      scene: "A single oil lamp glowing softly in surrounding darkness; the center stays calm and dark.",
    },

    // ───────────────────────── PART SIX ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Six", title: "Why Allah Made You" },
      theme: "light",
      cast: ["oasis"],
      scene: "A gentle oasis brimming with life and soft light, welcoming and warm.",
    },
    {
      type: "narrative",
      text: "Allah did not need to make you. He made you because He wanted to \u2014 as a gift of His love.",
      pos: "bottom",
      theme: "light",
      cast: ["mother-and-child"],
      scene: "A mother holding her baby close in warm tender light, partly turned away.",
    },
    {
      type: "narrative",
      text: "He made you to know Him, to love Him, and to live with kindness, honesty, and gratitude.",
      pos: "bottom",
      theme: "light",
      cast: ["oasis"],
      scene: "Soft golden light over a peaceful oasis, small birds drinking at the clear pool.",
    },
    {
      type: "narrative",
      text: "So that people would not forget Him, Allah chose certain humans to remind everyone of the truth.",
      pos: "top",
      theme: "dark",
      cast: ["arabian-desert"],
      scene: "A faint path winding through the desert toward a glow on the horizon; pale sky at the top.",
    },
    {
      type: "narrative",
      text: "These chosen humans are called prophets. A prophet is a person who carries God\u2019s message to others.",
      pos: "bottom",
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A gentle column of light descending toward a lone desert road, guiding and warm.",
    },
    {
      type: "narrative",
      text: "Allah sent many prophets \u2014 Adam, Noah, Abraham, Moses, Jesus \u2014 and last of all, Muhammad.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "A line of bright stars rising one after another across the night sky toward the horizon.",
    },
    {
      type: "narrative",
      text: "Every one of them taught the same simple truth: there is one God \u2014 so love Him, and be good.",
      pos: "top",
      theme: "dark",
      cast: ["light-of-revelation"],
      scene: "One steady source of light shining over the dark land; a pale calm sky at the top.",
    },
    {
      type: "narrative",
      text: "This book will tell you their stories, one by one. They are some of the best stories ever lived.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert"],
      scene: "An inviting desert road curving toward a glowing golden horizon, the start of a journey.",
    },

    // ───────────────────────── PART SEVEN ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Seven", title: "A Promise to Remember" },
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A wide warm dawn glow spreading softly across a calm horizon, full of hope.",
    },
    {
      type: "narrative",
      text: "If you forget everything else, remember this: Allah made you, Allah knows you, and Allah loves you.",
      pos: "bottom",
      theme: "light",
      cast: ["lantern-home"],
      scene: "A small warm-lit home held safe in a vast gentle landscape at dusk.",
    },
    {
      type: "narrative",
      text: "His mercy is bigger than any mistake, wider than the whole sky, and deeper than the deepest sea.",
      pos: "bottom",
      theme: "light",
      cast: ["sea-shore"],
      scene: "A vast calm sea meeting an endless dawn sky, a glowing path of light reaching to the horizon.",
    },
    {
      type: "quote",
      quote: {
        translation: "...My mercy encompasses all things.",
        source: "The Heights \u00b7 Qur\u2019an 7:156",
      },
      theme: "light",
      pos: "center",
      cast: ["light-of-revelation"],
      scene: "An immense embracing sky of warm light wrapping gently around the earth; calm darkened center.",
    },
    {
      type: "narrative",
      text: "He is waiting for you to turn to Him \u2014 and He is so happy whenever you do.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert"],
      scene: "A radiant sunrise breaking warmly over the dunes, a brand-new day beginning.",
    },
    {
      type: "arabic",
      arabic: { word: "\u0627\u0644\u0652\u062D\u064E\u0645\u0652\u062F\u064F \u0644\u0650\u0644\u0651\u0670\u0647", translit: "Alhamdulillah", meaning: "All praise and thanks belong to Allah \u2014 said for every good thing." },
      theme: "light",
      cast: ["oasis"],
      scene: "A lush oasis glowing with quiet gratitude in soft golden light; calm dark center.",
    },
    {
      type: "image",
      cast: ["light-of-revelation", "night-sky"],
      scene:
        "A closing wordless image: a doorway of warm light opening onto a starry desert road that " +
        "winds toward the horizon \u2014 the first step of a journey through the stories to come.",
    },
  ],
};

export default chapter;
