import type { Chapter } from "./types";

// Pages name canon entities in `cast` and describe only the scene/action; appearance comes from the
// canon. The Qur'an artwork must never contain legible text. Quotes are tagged by English chapter
// name and must be verified against an authentic translation.

const chapter: Chapter = {
  id: "what-is-the-quran",
  title: "What Is the Qur\u2019an?",
  subtitle: "Allah\u2019s own words, sent to guide the world",
  palette:
    "candlelit manuscript \u2014 deep teal and midnight blue with warm gold light, ivory pages and " +
    "soft drifting dust motes; reverent and glowing",
  pages: [
    // ───────────────────────── COVER ─────────────────────────
    {
      type: "cover",
      text: "What Is the Qur\u2019an?",
      cast: ["quran-book"],
      scene:
        "Title cover: the Qur\u2019an as a beautiful open illuminated manuscript on a carved wooden " +
        "stand, warm gold light glowing from its ivory pages, soft dust motes, deep teal shadows. " +
        "Render the title \"What Is the Qur\u2019an?\" in an elegant cream serif across the upper third.",
    },

    // ───────────────────────── PART ONE ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part One", title: "A Book Like No Other" },
      theme: "light",
      cast: ["quran-book"],
      scene: "The glowing open Qur\u2019an on its stand in a quiet dim room, light rising softly from the pages.",
    },
    {
      type: "narrative",
      text: "You have read many books. People write them \u2014 their own thoughts, their own stories. The Qur\u2019an is different.",
      pos: "bottom",
      theme: "light",
      cast: ["quran-book"],
      scene: "The open glowing manuscript resting alone on its wooden stand, warm and inviting.",
    },
    {
      type: "narrative",
      text: "Muslims believe the Qur\u2019an is not a person\u2019s book at all. Every word in it is the word of Allah, the one God.",
      pos: "top",
      theme: "dark",
      cast: ["light-of-revelation"],
      scene: "Soft rays of golden light descending from a calm night sky toward a glow below; pale calm sky at the top.",
    },
    {
      type: "narrative",
      text: "Allah sent it down to people to guide them, to comfort them, and to tell them the truth about everything.",
      pos: "bottom",
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A gentle ribbon of warm light reaching down from the stars toward the dark earth.",
    },
    {
      type: "narrative",
      text: "It is the most read, the most memorized, and one of the most loved books in the whole world.",
      pos: "bottom",
      theme: "light",
      cast: ["quran-book"],
      scene: "The luminous open Qur\u2019an glowing warmly, dust motes drifting in its light.",
    },
    {
      type: "arabic",
      arabic: { word: "\u0642\u064F\u0631\u0652\u0622\u0646", translit: "Qur\u2019an", meaning: "\u201cThe Recitation\u201d \u2014 Allah\u2019s words, meant to be read aloud and remembered." },
      theme: "light",
      cast: ["oil-lamp"],
      scene: "A single oil lamp glowing softly in the dark; the center stays calm and dark.",
    },
    {
      type: "narrative",
      text: "The word \u201cQur\u2019an\u201d means \u201cthe Recitation\u201d \u2014 because it is meant to be spoken aloud, not just kept on a shelf.",
      pos: "bottom",
      theme: "light",
      cast: ["oil-lamp"],
      scene: "Warm lamplight pooling gently on a dark surface, intimate and quiet.",
    },
    {
      type: "quote",
      quote: {
        translation: "This is the Book about which there is no doubt, a guidance for those mindful of Allah.",
        source: "The Cow \u00b7 Qur\u2019an 2:2",
      },
      theme: "light",
      pos: "center",
      cast: ["quran-book"],
      scene: "The glowing open Qur\u2019an at the heart of a calm dim scene; a gently darkened center band for text.",
    },

    // ───────────────────────── PART TWO ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Two", title: "How It Came Down" },
      theme: "light",
      cast: ["cave-hira"],
      scene: "The cave of Hira high on a dark mountain at dusk, the desert valley far below, first stars above.",
    },
    {
      type: "narrative",
      text: "About 1,400 years ago, in the deserts of Arabia, there lived a man named Muhammad, known for his honesty.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert"],
      scene: "A vast quiet desert at golden hour, soft and open, far hills in the haze.",
    },
    {
      type: "narrative",
      text: "He would often go alone to a quiet cave in the mountains to sit, and to think about God and the world.",
      pos: "top",
      theme: "dark",
      cast: ["cave-hira"],
      scene: "The small dark cave opening on the mountainside at dusk; a pale calm strip of sky at the top.",
    },
    {
      type: "narrative",
      text: "One night, when he was forty years old, the cave suddenly filled with light, and an angel appeared.",
      pos: "bottom",
      theme: "light",
      cast: ["gabriel", "cave-hira"],
      scene: "The cave mouth flooded with overwhelming silver-gold light pouring in, awe and stillness, no human figure.",
    },
    {
      type: "narrative",
      text: "An angel is a being of light that Allah creates to carry out His commands. This angel was named Gabriel.",
      pos: "top",
      theme: "dark",
      cast: ["gabriel"],
      scene: "Vast luminous wing-like sweeps of silver-gold radiance against deep indigo; pale calm space at the top.",
    },
    {
      type: "narrative",
      text: "Gabriel brought the very first words of the Qur\u2019an. His first command to Muhammad was simple: \u201cRead.\u201d",
      pos: "bottom",
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A radiant beam of golden light descending into a dark cave space, sacred and quiet.",
    },
    {
      type: "quote",
      quote: {
        translation: "Read! In the name of your Lord who created \u2014 created the human being from a clinging clot.",
        source: "The Clinging Clot \u00b7 Qur\u2019an 96:1-2",
      },
      theme: "light",
      pos: "center",
      cast: ["light-of-revelation"],
      scene: "A pure column of light meeting darkness, the first words arriving; calm darkened center.",
    },
    {
      type: "narrative",
      text: "Muhammad could not read or write a single word \u2014 yet he remembered everything Gabriel gave him, perfectly.",
      pos: "bottom",
      theme: "light",
      cast: ["cave-hira"],
      scene: "A soft warm glow lingering inside the quiet cave mouth, the valley dim far below.",
    },
    {
      type: "narrative",
      text: "The Qur\u2019an did not arrive all at once. It came down a little at a time, over twenty-three years.",
      pos: "top",
      theme: "dark",
      cast: ["night-sky"],
      scene: "An immense starry sky over still dunes, time stretching out; a pale calm region at the top.",
    },
    {
      type: "narrative",
      text: "Piece by piece, Allah\u2019s words answered people\u2019s questions and guided them through every kind of day.",
      pos: "bottom",
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "Gentle threads of light descending one after another toward the quiet earth.",
    },

    // ───────────────────────── PART THREE ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Three", title: "Made to Be Heard" },
      theme: "light",
      cast: ["night-sky"],
      scene: "A serene starlit sky over a hushed desert, as if waiting to listen.",
    },
    {
      type: "narrative",
      text: "The Qur\u2019an was given in the Arabic language, and it is recited aloud in a flowing, almost musical way.",
      pos: "bottom",
      theme: "light",
      cast: ["quran-book"],
      scene: "The open glowing manuscript, warm light rising as if its pages were singing.",
    },
    {
      type: "narrative",
      text: "Its sound is so beautiful that even people who do not speak Arabic have wept simply from listening.",
      pos: "bottom",
      theme: "light",
      cast: ["lantern-home"],
      scene: "A warm-lit window glowing in the blue dusk, someone resting near it listening, seen from outside.",
    },
    {
      type: "narrative",
      text: "When it is recited, many feel a deep calm, as if the words are speaking straight into their heart.",
      pos: "top",
      theme: "dark",
      cast: ["lantern-home"],
      scene: "A single soft-lit home under a vast peaceful dusk sky; a pale calm strip of sky at the top.",
    },
    {
      type: "arabic",
      arabic: { word: "\u0622\u064A\u0629", translit: "Ayah", meaning: "A verse of the Qur\u2019an \u2014 the same word also means a \u2018sign\u2019 of Allah." },
      theme: "light",
      cast: [],
      scene: "A single leaf backlit by soft golden light against a calm dark field; the center stays calm and dark.",
    },
    {
      type: "narrative",
      text: "Each small piece of the Qur\u2019an is called an ayah. The very same word means a \u201csign\u201d \u2014 like the signs in creation.",
      pos: "bottom",
      theme: "light",
      cast: ["great-tree"],
      scene: "A great tree with light glowing through its leaves, each leaf like a tiny sign.",
    },
    {
      type: "narrative",
      text: "A whole group of ayahs together is called a chapter. The Qur\u2019an has 114 chapters in all.",
      pos: "bottom",
      theme: "light",
      cast: ["quran-book"],
      scene: "The open Qur\u2019an, soft golden light across its glowing pages.",
    },
    {
      type: "narrative",
      text: "Each chapter has a name \u2014 like \u201cThe Opening,\u201d \u201cThe Light,\u201d or \u201cMary\u201d \u2014 names we will meet in these stories.",
      pos: "top",
      theme: "dark",
      cast: ["light-of-revelation"],
      scene: "Soft beams of light fanning across a calm sky; pale calm space at the top.",
    },

    // ───────────────────────── PART FOUR ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Four", title: "Kept Perfectly Safe" },
      theme: "light",
      cast: ["quran-book"],
      scene: "The glowing Qur\u2019an held in a warm pool of protective light in the surrounding dark.",
    },
    {
      type: "narrative",
      text: "Allah Himself promised to protect the Qur\u2019an, so that it could never be lost or changed.",
      pos: "bottom",
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A soft dome of warm light gently shielding a glow below, like a guarding hand of light.",
    },
    {
      type: "quote",
      quote: {
        translation: "Indeed, it is We who sent down the Reminder, and indeed, We will be its guardian.",
        source: "The Rocky Tract \u00b7 Qur\u2019an 15:9",
      },
      theme: "light",
      pos: "center",
      cast: ["light-of-revelation"],
      scene: "Light wrapping protectively around a calm horizon; a gently darkened center for text.",
    },
    {
      type: "narrative",
      text: "It was kept safe in two ways at once: written down with great care, and memorized by heart.",
      pos: "bottom",
      theme: "light",
      cast: ["reed-pen"],
      scene: "A reed pen and inkpot beside a blank sheet of parchment in warm lamplight.",
    },
    {
      type: "narrative",
      text: "From the very start, people wrote down each new verse and learned it, word for word, by heart.",
      pos: "top",
      theme: "dark",
      cast: ["reed-pen"],
      scene: "Warm lamplight over a writing table with blank parchment and a reed pen; pale calm space at the top.",
    },
    {
      type: "narrative",
      text: "Allah made the Qur\u2019an easy to remember, so that millions of people could carry it inside them.",
      pos: "bottom",
      theme: "light",
      cast: ["quran-book"],
      scene: "The open glowing Qur\u2019an, light spilling warmly outward into the room.",
    },
    {
      type: "quote",
      quote: {
        translation: "And We have certainly made the Qur\u2019an easy to remember. So is there anyone who will be reminded?",
        source: "The Moon \u00b7 Qur\u2019an 54:17",
      },
      theme: "light",
      pos: "center",
      cast: ["quran-book"],
      scene: "The luminous Qur\u2019an in a calm dim space; a softly darkened center band for text.",
    },
    {
      type: "narrative",
      text: "A person who memorizes the entire Qur\u2019an is called a hafiz \u2014 a \u201ckeeper\u201d of Allah\u2019s words.",
      pos: "bottom",
      theme: "light",
      cast: ["children-reading"],
      scene: "Children reading open books together in warm lamplight, faces turned softly down to the pages.",
    },
    {
      type: "narrative",
      text: "Even today, young children become huffaz, able to recite the whole book aloud from memory.",
      pos: "top",
      theme: "dark",
      cast: ["children-reading"],
      scene: "A gentle lamplit circle of children with open books; a pale calm space at the top.",
    },
    {
      type: "narrative",
      text: "Because of this, the Qur\u2019an today is exactly the same as it was 1,400 years ago \u2014 not one word changed.",
      pos: "bottom",
      theme: "light",
      cast: ["quran-book"],
      scene: "The timeless glowing Qur\u2019an, steady and unchanged in its warm light.",
    },

    // ───────────────────────── PART FIVE ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Five", title: "What Is Inside" },
      theme: "light",
      cast: ["quran-book"],
      scene: "The open Qur\u2019an glowing, as if about to share everything it holds.",
    },
    {
      type: "narrative",
      text: "So what does the Qur\u2019an actually say? First of all, it tells us who Allah is, and how much He loves us.",
      pos: "bottom",
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "Warm radiant light glowing over a calm horizon, full of gentle love.",
    },
    {
      type: "narrative",
      text: "It is full of the stories of the prophets \u2014 Adam, Noah, Abraham, Moses, Mary, Jesus, and many more.",
      pos: "top",
      theme: "dark",
      cast: ["night-sky"],
      scene: "A line of bright stars rising across the night sky, one after another; pale calm space at the top.",
    },
    {
      type: "narrative",
      text: "It teaches us how to live: to be honest, kind, patient, fair, and grateful in everything we do.",
      pos: "bottom",
      theme: "light",
      cast: ["scales"],
      scene: "A pair of bronze balance scales resting perfectly level in warm light.",
    },
    {
      type: "narrative",
      text: "It comforts the sad, gives hope to the worried, and reminds us that we are never, ever alone.",
      pos: "bottom",
      theme: "light",
      cast: ["lantern-home"],
      scene: "A small warm-lit home glowing safely in a vast gentle dusk landscape.",
    },
    {
      type: "narrative",
      text: "And it points to Allah\u2019s signs all around us \u2014 the sky, the rain, the sea, and even our own selves.",
      pos: "top",
      theme: "dark",
      cast: ["rain-and-greenery"],
      scene: "Gentle rain reviving dry earth into fresh green; a pale calm sky at the top.",
    },
    {
      type: "narrative",
      text: "Everything in it leads to the same place: knowing Allah, and living the way that He loves.",
      pos: "bottom",
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A single steady source of light over the calm dark land, drawing everything toward it.",
    },

    // ───────────────────────── PART SIX ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Six", title: "How Muslims Love It" },
      theme: "light",
      cast: ["quran-book"],
      scene: "The glowing Qur\u2019an resting gently on its stand, cared for and cherished.",
    },
    {
      type: "narrative",
      text: "Because the Qur\u2019an is Allah\u2019s own words, Muslims treat it with great care and deep respect.",
      pos: "bottom",
      theme: "light",
      cast: ["quran-book"],
      scene: "The Qur\u2019an held in soft reverent light, clean and beautiful on its wooden stand.",
    },
    {
      type: "narrative",
      text: "They keep it clean and held up high, open it gently, and quiet their hearts before they read.",
      pos: "top",
      theme: "dark",
      cast: ["quran-book"],
      scene: "The closed decorated manuscript resting on a high clean shelf in warm light; pale calm space at the top.",
    },
    {
      type: "narrative",
      text: "Many Muslims read a little of it every single day, and recite its verses inside their prayers.",
      pos: "bottom",
      theme: "light",
      cast: ["lantern-home"],
      scene: "A warm-lit home at dawn, a soft glow at the window, a peaceful start to the day.",
    },
    {
      type: "narrative",
      text: "Children learn it slowly, a few verses at a time, often by lamplight beside someone they love.",
      pos: "bottom",
      theme: "light",
      cast: ["children-reading"],
      scene: "Children gathered around open books in cozy lamplight, faces turned softly down to the pages.",
    },
    {
      type: "narrative",
      text: "The more they read it, the more they understand \u2014 it is a book you can keep growing up inside.",
      pos: "top",
      theme: "dark",
      cast: ["children-reading"],
      scene: "A gentle lamplit reading circle; a pale calm space at the top of the frame.",
    },

    // ───────────────────────── PART SEVEN ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Seven", title: "For You" },
      theme: "light",
      cast: ["quran-book"],
      scene: "The open glowing Qur\u2019an turned gently toward the viewer, warm and welcoming.",
    },
    {
      type: "narrative",
      text: "You do not need to know Arabic to begin. You can start with its meaning, and with its stories.",
      pos: "bottom",
      theme: "light",
      cast: ["quran-book"],
      scene: "The luminous open manuscript inviting the reader closer in soft golden light.",
    },
    {
      type: "narrative",
      text: "That is what this whole book is \u2014 some of the most beautiful stories from the Qur\u2019an, told just for you.",
      pos: "bottom",
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "Warm light opening across a calm horizon like a welcome, full of promise.",
    },
    {
      type: "narrative",
      text: "As you read them, remember: these are not just tales. They are Allah\u2019s gift, sent to guide you home.",
      pos: "top",
      theme: "dark",
      cast: ["arabian-desert"],
      scene: "An inviting desert road curving toward a glowing horizon; a pale calm sky at the top.",
    },
    {
      type: "arabic",
      arabic: { word: "\u0628\u0650\u0633\u0652\u0645\u0650 \u0627\u0644\u0644\u0647", translit: "Bismillah", meaning: "\u201cIn the name of Allah\u201d \u2014 said before reading, eating, or starting anything good." },
      theme: "light",
      cast: ["oil-lamp"],
      scene: "A single oil lamp glowing softly in the dark, ready at the start of something good; calm dark center.",
    },
    {
      type: "image",
      cast: ["quran-book"],
      scene:
        "A closing wordless image: the open glowing Qur\u2019an on its stand, warm light rising from it " +
        "like a soft dawn, inviting the reader onward into the stories it holds.",
    },
  ],
};

export default chapter;
