import type { Chapter } from "./types";

// Muhammad's face is NEVER shown (enforced by the canon's faceless depiction rule). Pages name
// canon entities in `cast` and describe only the scene/action — appearance comes from the canon.
// Quotes are tagged by English chapter name and must be verified against an authentic translation.

const chapter: Chapter = {
  id: "prophet-muhammad",
  title: "Prophet Muhammad ﷺ",
  subtitle: "The life and message of the final prophet",
  palette:
    "warm sand, terracotta, dusty rose and honey gold by day, deepening to indigo and silver " +
    "starlight by night; the soft green dome of Medina at the close",
  pages: [
    // ───────────────────────── COVER ─────────────────────────
    {
      type: "cover",
      text: "Prophet Muhammad ﷺ",
      cast: ["mecca", "kaaba", "caravan"],
      scene:
        "Title cover, golden hour over the valley town of Mecca: the plain stone Kaaba small and " +
        "respectful in the valley, a caravan on the far ridge. Render the title \"Prophet Muhammad\" " +
        "in an elegant cream serif across the upper third.",
    },

    // ───────────────────────── PART ONE ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part One", title: "Before We Begin" },
      theme: "light",
      cast: ["arabian-desert", "caravan"],
      scene: "A vast desert at first light, one tiny caravan silhouette far on a ridge.",
    },
    {
      type: "narrative",
      text: "This is the story of a man named Muhammad, and of the message he carried to the whole world.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert", "caravan"],
      scene: "A wide dawn desert, a single caravan crossing far on the horizon.",
    },
    {
      type: "narrative",
      text: "To understand him, we begin with one simple idea: there is one God who made everything that exists.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "An immense star-filled night sky arching over quiet dunes, a deep indigo hush.",
    },
    {
      type: "arabic",
      arabic: { word: "الله", translit: "Allah", meaning: "The one God — the Maker of all things. \"Allah\" and \"God\" mean the same." },
      theme: "light",
      cast: [],
      scene: "A warm radiant glow rising LOW over a calm desert horizon at dusk; the center stays calm and dark.",
    },
    {
      type: "narrative",
      text: "Muslims believe God has no shape and no equal. We cannot see Him, yet all around us are signs that He is there.",
      pos: "top",
      theme: "dark",
      cast: ["arabian-desert"],
      scene: "Sunlight breaking through soft clouds over distant mountains, rays spilling onto the land; no figure.",
    },
    {
      type: "narrative",
      text: "God made people to know Him and to be good — kind, honest, and grateful for all He gives.",
      pos: "bottom",
      theme: "light",
      cast: ["oasis"],
      scene: "A clear oasis spring ringed by palms, small birds drinking, gentle golden light.",
    },
    {
      type: "narrative",
      text: "So people would not forget Him, God chose certain humans to remind them. These messengers are called prophets.",
      pos: "top",
      theme: "dark",
      cast: ["arabian-desert"],
      scene: "A faint path winding through the desert toward a glow on the horizon, footprints in the sand.",
    },
    {
      type: "arabic",
      arabic: { word: "نَبِيّ", translit: "Nabī", meaning: "A prophet — a person God chooses to carry His message to others." },
      theme: "light",
      cast: ["oil-lamp"],
      scene: "A single oil lamp glowing warmly on a desert rock at dusk, soft darkness around it.",
    },
    {
      type: "narrative",
      text: "A prophet is not a god. He is a human who lives and sleeps like us — but he speaks the words God gives him.",
      pos: "bottom",
      theme: "light",
      cast: ["oil-lamp"],
      scene: "A humble desert home at night, warm lamplight glowing in an open doorway; no figures visible.",
    },
    {
      type: "narrative",
      text: "There were many prophets before — Adam, Noah, Abraham, Moses, and Jesus among them. Muhammad was the last.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert"],
      scene: "A long range of mountain peaks receding into soft mist, many summits in a line.",
    },
    {
      type: "narrative",
      text: "His life still shapes how more than a billion people pray, give, and treat one another today.",
      pos: "top",
      theme: "dark",
      cast: ["crescent-moon"],
      scene: "A warm aerial of many small lamplit homes nestled across hills at twilight beneath a slim crescent.",
    },

    // ───────────────────────── PART TWO ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Two", title: "The World He Was Born Into" },
      theme: "light",
      cast: ["arabian-desert"],
      scene: "A sweeping golden desert of dunes and rocky hills at midday, immense and empty.",
    },
    {
      type: "narrative",
      text: "About 1,400 years ago lay a vast, dry land of sand and stone — the desert of Arabia.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert"],
      scene: "An immense sunlit desert of dunes and dark rock, heat shimmer on the horizon.",
    },
    {
      type: "narrative",
      text: "Today we call this land Saudi Arabia. Back then it had few roads and little water — only towns and wandering tribes.",
      pos: "top",
      theme: "dark",
      cast: ["arabian-desert"],
      scene: "A high storybook map-like view of tan desert dotted with small green oases and faint trails.",
    },
    {
      type: "narrative",
      text: "In the heart of it stood a town called Mecca, a resting place for traders crossing the sands.",
      pos: "bottom",
      theme: "light",
      cast: ["mecca"],
      scene: "Mecca in its valley between bare hills, market tents and palms, warm light, seen at a distance.",
    },
    {
      type: "narrative",
      text: "At the center of Mecca was a simple cube-shaped house of stone, called the Kaaba.",
      pos: "bottom",
      theme: "light",
      cast: ["kaaba"],
      scene: "The plain stone Kaaba standing in an open dusty courtyard at midday, seen from a respectful distance.",
    },
    {
      type: "narrative",
      text: "Long before, the prophet Abraham had built it as a place to worship the one God.",
      pos: "top",
      theme: "dark",
      cast: ["kaaba"],
      scene: "The ancient stone cube beneath a bright clear sky, weathered and reverent, light warming its edges.",
    },
    {
      type: "arabic",
      arabic: { word: "الْكَعْبَة", translit: "al-Kaʿbah", meaning: "The Kaaba — the cube-shaped house of worship at the center of Mecca." },
      theme: "light",
      cast: ["kaaba"],
      scene: "The stone cube at dusk lit by a soft warm glow, calm darkness around it.",
    },
    {
      type: "narrative",
      text: "But over the years people forgot. They filled the Kaaba with idols — statues they prayed to instead of God.",
      pos: "bottom",
      theme: "light",
      era: "before Islam",
      cast: ["mecca@idol-era"],
      scene: "A dim courtyard with vague carved-stone idol statues standing in shadow, a heavy somber mood.",
    },
    {
      type: "narrative",
      text: "The people of Mecca lived in tribes — large families and clans who often quarreled and fought.",
      pos: "top",
      theme: "dark",
      cast: ["people"],
      scene: "Two groups of robed figures at a distance facing each other across a dusty street, tension in the air.",
    },
    {
      type: "narrative",
      text: "The strong took from the weak. The poor were ignored, and many people were bought and sold as slaves.",
      pos: "bottom",
      theme: "light",
      cast: ["people", "desert-market"],
      scene: "A hard desert market seen from a distance, heavy loads and bowed figures, a somber muted palette.",
    },
    {
      type: "narrative",
      text: "Into this troubled world, in the year 570, a baby boy was born.",
      pos: "top",
      theme: "dark",
      cast: ["mecca"],
      scene: "A single warm-lit window glowing in a dark stone house at night, one bright star above it.",
    },

    // ───────────────────────── PART THREE ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Three", title: "A Boy Named Muhammad" },
      theme: "light",
      cast: ["mecca"],
      scene: "Soft dawn over the rooftops of old Mecca, gentle rose light, a single fading star.",
    },
    {
      type: "narrative",
      text: "His name was Muhammad, which means \"the praised one.\"",
      pos: "bottom",
      theme: "light",
      cast: ["mecca"],
      scene: "Dawn light spilling warmly across the stone rooftops of Mecca, palms catching the glow.",
    },
    {
      type: "arabic",
      arabic: { word: "مُحَمَّد", translit: "Muhammad", meaning: "\"The praised one\" — the name of the final prophet." },
      theme: "light",
      cast: [],
      scene: "A radiant warm glow over a calm desert horizon at first light, gold over rose; calm dark center.",
    },
    {
      type: "narrative",
      text: "His father had died before he was born. When Muhammad was six years old, his mother died too.",
      pos: "bottom",
      theme: "light",
      cast: ["muhammad@shepherd-boy"],
      scene: "The small faceless boy, seen from behind, alone on a wide quiet desert path at dusk, long soft shadows.",
    },
    {
      type: "narrative",
      text: "He was an orphan — a child with no mother or father to raise him.",
      pos: "top",
      theme: "dark",
      cast: ["oil-lamp"],
      scene: "An empty doorway of a stone home at golden hour, a single small lamp inside, stillness and quiet.",
    },
    {
      type: "narrative",
      text: "His grandfather cared for him, and then his kind uncle, Abu Talib, took him in.",
      pos: "bottom",
      theme: "light",
      cast: ["muhammad@shepherd-boy"],
      scene: "A large protective adult hand and the small boy's hand walking together as warm silhouettes at sunset.",
    },
    {
      type: "narrative",
      text: "As a boy, Muhammad worked as a shepherd, watching over sheep in the hills outside Mecca.",
      pos: "top",
      theme: "dark",
      cast: ["muhammad@shepherd-boy", "arabian-desert"],
      scene: "A flock of sheep grazing on a rocky golden hillside at morning, the faceless shepherd boy at a distance.",
    },
    {
      type: "narrative",
      text: "He grew into a young man known for one thing above all: he never lied and never cheated anyone.",
      pos: "bottom",
      theme: "light",
      cast: ["desert-market", "scales"],
      scene: "A bustling honest marketplace at golden hour — balanced scales, baskets of dates, folded fabrics.",
    },
    {
      type: "narrative",
      text: "People trusted him so completely that they nicknamed him Al-Amin — \"the trustworthy one.\"",
      pos: "top",
      theme: "dark",
      cast: ["people"],
      scene: "A pair of hands gently placing a wrapped valuable parcel into another's waiting hands, a feeling of trust.",
    },
    {
      type: "narrative",
      text: "We will call him Muhammad — but to everyone who knew him, he was simply the one you could trust.",
      pos: "bottom",
      theme: "light",
      cast: ["mecca", "people"],
      scene: "A warm courtyard at golden hour with distant figures gathered peacefully.",
    },
    {
      type: "narrative",
      text: "A wise, successful merchant named Khadijah saw his honesty and hired him to lead her caravans.",
      pos: "top",
      theme: "dark",
      cast: ["caravan"],
      scene: "A trade caravan of laden camels setting out across the desert at dawn, soft dust, hopeful light.",
    },
    {
      type: "narrative",
      text: "She came to admire him deeply, and they married. Khadijah was the first to believe in him.",
      pos: "bottom",
      theme: "light",
      cast: ["oil-lamp"],
      scene: "Two warm lamps glowing side by side in a window at night, a quiet symbol of partnership, deep indigo around.",
    },
    {
      type: "narrative",
      text: "One year the people of Mecca repaired the Kaaba. But when the work was done, they began to argue.",
      pos: "bottom",
      theme: "light",
      cast: ["kaaba@under-repair"],
      scene: "The stone Kaaba wrapped in wooden scaffolding, workers at a distance, dust and golden light.",
    },
    {
      type: "narrative",
      text: "Each tribe wanted the honor of lifting the holy Black Stone back into the Kaaba's corner.",
      pos: "top",
      theme: "dark",
      cast: ["kaaba@under-repair", "black-stone", "people"],
      scene: "Groups of robed figures in tense clusters around the Kaaba, the dark stone on a cloth between them, seen from above.",
    },
    {
      type: "narrative",
      text: "They nearly came to blows. So they agreed: the next person to arrive would decide. It was Muhammad.",
      pos: "bottom",
      theme: "light",
      cast: ["muhammad@young-trader", "kaaba"],
      scene: "A single faceless robed figure arriving through a stone archway into the courtyard, bright light behind.",
    },
    {
      type: "narrative",
      text: "He laid his cloak on the ground, placed the stone in its center, and called a leader from every tribe.",
      pos: "top",
      theme: "dark",
      cast: ["the-cloak", "black-stone", "people"],
      scene: "The cloak spread on the ground with the dark stone at its center; many hands from differently colored sleeves grip the edges to lift it together. Hands and cloth only.",
    },
    {
      type: "narrative",
      text: "No one was left out, and no one was first. Even young, Muhammad turned anger into peace.",
      pos: "bottom",
      theme: "light",
      cast: ["black-stone", "kaaba"],
      scene: "A single pair of careful hands gently setting the dark stone into the corner of the Kaaba, warm light, calm.",
    },

    // ───────────────────────── PART FOUR ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Four", title: "The Cave and the First Words" },
      theme: "light",
      cast: ["cave-hira"],
      scene: "The rocky mountain at dusk with the small cave opening high up, the town glowing far below, first stars.",
    },
    {
      type: "narrative",
      text: "As Muhammad grew older, the unfairness of Mecca weighed on his heart — the idols, the cruelty, the forgotten poor.",
      pos: "bottom",
      theme: "light",
      era: "around 610 CE",
      cast: ["mecca", "muhammad@age-40"],
      scene: "Mecca seen from a hilltop at dusk, the lone faceless figure looking out over the town, thoughtful and heavy.",
    },
    {
      type: "narrative",
      text: "He began to go alone to a cave high on a mountain near Mecca — to sit, to think, and to pray.",
      pos: "top",
      theme: "dark",
      cast: ["cave-hira"],
      scene: "The small dark cave opening high on the steep rocky mountain, a vast view of desert far below, soft evening light.",
    },
    {
      type: "arabic",
      arabic: { word: "حِرَاء", translit: "Hira", meaning: "The cave on the Mountain of Light where Muhammad went to pray." },
      theme: "light",
      cast: ["cave-hira"],
      scene: "A lone mountain peak at dusk with a faint glow near its summit, deep indigo around it.",
    },
    {
      type: "narrative",
      text: "He was now a grown man of forty. One night, in the quiet dark of the cave, everything changed.",
      pos: "bottom",
      theme: "light",
      era: "around 610 CE, age forty",
      cast: ["cave-hira"],
      scene: "The mouth of the mountain cave at night, brilliant stars above, a soft glow within, profound stillness; no figure.",
    },
    {
      type: "narrative",
      text: "A being of light filled the cave — an angel. Angels are beings God makes from light to carry out His will.",
      pos: "top",
      theme: "dark",
      cast: ["gabriel", "cave-hira"],
      scene: "The cave interior flooded with overwhelming silver-gold light pouring in from the night sky; only radiance.",
    },
    {
      type: "arabic",
      arabic: { word: "مَلَك", translit: "Malak", meaning: "An angel — a being of light created by God to serve Him and deliver His messages." },
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A soft column of radiant light descending into darkness, gentle glowing particles; calm dark center.",
    },
    {
      type: "narrative",
      text: "This was Gabriel, the mightiest angel — the one God sends to bring His words to His prophets.",
      pos: "bottom",
      theme: "light",
      cast: ["gabriel"],
      scene: "Overwhelming radiant light and stars blazing above a dark mountain peak, awe and majesty.",
    },
    {
      type: "narrative",
      text: "Gabriel had come to prophets before — to Abraham, to Moses, to Mary, the mother of Jesus.",
      pos: "top",
      theme: "dark",
      cast: ["light-of-revelation", "night-sky"],
      scene: "A great gentle column of light connecting the heavens to distant mountains across a starlit land.",
    },
    {
      type: "narrative",
      text: "\"Read!\" the angel commanded. \"But I cannot read,\" Muhammad answered, for he had never been taught.",
      pos: "bottom",
      theme: "light",
      cast: ["gabriel", "muhammad@age-40", "cave-hira"],
      scene: "The cave interior bright with pouring light; the single faceless figure draws back in awe as a silhouette against the glow.",
    },
    {
      type: "narrative",
      text: "The command came again, and then — by God's will — words rose to his lips that he had never known.",
      pos: "top",
      theme: "dark",
      cast: ["light-of-revelation", "cave-hira"],
      scene: "Radiant light filling the cave with swirling glowing motes like luminous dust, sacred and alive.",
    },
    {
      type: "arabic",
      arabic: { word: "اقْرَأْ", translit: "Iqra", meaning: "\"Read\" or \"Recite\" — the very first word God revealed to Muhammad." },
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A single shaft of warm light breaking through darkness, gentle and luminous; calm dark center.",
    },
    {
      type: "quote",
      quote: {
        translation:
          "Read in the name of your Lord who created — created man from a clinging clot. Read, and your " +
          "Lord is the Most Generous, who taught by the pen — taught man what he did not know.",
        source: "The Clinging Clot · Qur'an 96:1-5",
        arabic: "اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ",
      },
      theme: "light",
      pos: "center",
      cast: ["light-of-revelation", "cave-hira"],
      scene: "A luminous night sky opening over dark mountains, a soft radiant column of light from the heavens to the earth.",
    },
    {
      type: "narrative",
      text: "These were the very first words of the Qur'an, the holy book God would reveal to him.",
      pos: "bottom",
      theme: "light",
      cast: ["cave-hira"],
      scene: "Fading starlight over the mountain as dawn approaches, a soft hush after a great moment.",
    },
    {
      type: "narrative",
      text: "Shaking with awe, Muhammad hurried home. Khadijah wrapped him warmly and said God would not forsake him.",
      pos: "top",
      theme: "dark",
      cast: ["oil-lamp"],
      scene: "A warm home interior at night, a soft blanket and two glowing lamps, comfort and tenderness.",
    },

    // ───────────────────────── PART FIVE ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Five", title: "What Is the Qur'an" },
      theme: "light",
      cast: ["night-sky"],
      scene: "A serene desert night with a sky of turning stars and soft ribbons of light, vast and reverent.",
    },
    {
      type: "narrative",
      text: "From that night, God's words came to Muhammad little by little, over twenty-three years.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "Star trails wheeling slowly across a deep night sky above the quiet desert, the passing of time.",
    },
    {
      type: "narrative",
      text: "All these words together are called the Qur'an. The name means \"the recitation\" — words read aloud.",
      pos: "top",
      theme: "dark",
      cast: ["light-of-revelation"],
      scene: "An open desert at soft daylight with gentle abstract ribbons of light rising like sound waves, calm and luminous.",
    },
    {
      type: "arabic",
      arabic: { word: "الْقُرْآن", translit: "al-Qurʾān", meaning: "The Qur'an — God's words given to Muhammad, the holy book of Islam." },
      theme: "light",
      cast: ["light-of-revelation"],
      scene: "A soft radiant glow over a calm horizon at dusk, gold and indigo; calm dark center.",
    },
    {
      type: "narrative",
      text: "Muhammad did not write the Qur'an. He could not read or write — he only spoke the words God gave him.",
      pos: "bottom",
      theme: "light",
      cast: ["reed-pen"],
      scene: "A simple reed pen resting unused beside a warm oil lamp on a wooden surface; the true light comes from above.",
    },
    {
      type: "narrative",
      text: "His companions wrote the words down, and many people learned the entire Qur'an by heart.",
      pos: "top",
      theme: "dark",
      cast: ["reed-pen"],
      scene: "Hands resting on blank parchment beside a glowing lamp at night, reverent and careful; no visible writing.",
    },
    {
      type: "narrative",
      text: "Even today, millions of people have memorized every word — unchanged for fourteen hundred years.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "A wide twilight view of many distant lamplit places scattered across hills and valleys, connected by soft light.",
    },
    {
      type: "narrative",
      text: "Muslims believe the Qur'an is God speaking to us — guiding how to live, to be just, and to love.",
      pos: "top",
      theme: "dark",
      cast: ["sea-shore"],
      scene: "A gentle sunrise over a calm sea meeting a soft shore, a glowing path of light on the water, guidance and peace.",
    },
    {
      type: "narrative",
      text: "Its words are also beautiful to hear. Their rhythm alone can move a listener to tears.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "A still desert night with delicate ripples of soft light spreading outward like a quiet melody.",
    },

    // ───────────────────────── PART SIX ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Six", title: "His Message" },
      theme: "light",
      cast: ["mecca"],
      scene: "Dawn light spreading across the desert and the rooftops of Mecca, warm and awakening.",
    },
    {
      type: "narrative",
      text: "Muhammad began to teach what God had told him. His message was simple, but it changed the world.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert"],
      scene: "Warm dawn light sweeping over a town and the wide desert beyond, a feeling of new beginning.",
    },
    {
      type: "narrative",
      text: "First: there is only one God. Stop praying to idols of stone, and worship the Maker of all alone.",
      pos: "top",
      theme: "dark",
      cast: ["kaaba", "mecca@idol-era"],
      scene: "A single bright shaft of light falling on the Kaaba courtyard while shadowy idols are left behind in darkness.",
    },
    {
      type: "arabic",
      arabic: { word: "تَوْحِيد", translit: "Tawhid", meaning: "Believing in and worshiping one God alone — the heart of Islam." },
      theme: "light",
      cast: [],
      scene: "One radiant point of light glowing in a vast calm darkness, simple and pure; calm dark center.",
    },
    {
      type: "narrative",
      text: "He taught people to be honest, to keep their promises, and to treat one another fairly.",
      pos: "bottom",
      theme: "light",
      cast: ["scales", "desert-market"],
      scene: "A fair marketplace exchange at golden hour with perfectly balanced scales; hands only.",
    },
    {
      type: "narrative",
      text: "He told the rich to care for the poor, the orphan, and the traveler who had nothing.",
      pos: "top",
      theme: "dark",
      cast: ["dates-and-bread"],
      scene: "Hands offering bread and dates into small outstretched hands, warm light, gentle compassion.",
    },
    {
      type: "narrative",
      text: "He taught that women were to be honored, not mistreated — and that daughters were a blessing.",
      pos: "bottom",
      theme: "light",
      cast: [],
      scene: "A tender home scene at golden hour with a small bunch of desert flowers held in a child's hands, soft and loving.",
    },
    {
      type: "narrative",
      text: "He urged people to free those they had enslaved, and to be gentle even with animals.",
      pos: "top",
      theme: "dark",
      cast: ["oasis"],
      scene: "A hand pouring water for a tired camel while a small cat rests nearby in warm light, kindness in a small act.",
    },
    {
      type: "narrative",
      text: "And no one, he taught, is better for their tribe or the color of their skin — only for their goodness.",
      pos: "bottom",
      theme: "light",
      cast: ["people"],
      scene: "Many hands of different skin tones joined together in a circle in warm light, unity and equality; hands only.",
    },
    {
      type: "narrative",
      text: "But the powerful men of Mecca grew angry. His message threatened their idols and their pride.",
      pos: "top",
      theme: "dark",
      cast: ["people", "mecca"],
      scene: "A cluster of dark robed figures at a distance beneath a heavy, brooding sky, tension and threat.",
    },
    {
      type: "narrative",
      text: "Muhammad and his followers were mocked and harmed, and yet he answered cruelty with patience.",
      pos: "bottom",
      theme: "light",
      cast: ["people", "arabian-desert"],
      scene: "A small group of faceless travelers standing firm against a hard wind at dusk, resolve and patience.",
    },
    {
      type: "narrative",
      text: "At last they left Mecca for a city to the north called Medina, where the people welcomed them.",
      pos: "top",
      theme: "dark",
      cast: ["medina-mosque", "caravan"],
      scene: "A green-fringed town of date palms at golden hour welcoming a small caravan arriving from the desert.",
    },
    {
      type: "arabic",
      arabic: { word: "الْهِجْرَة", translit: "al-Hijrah", meaning: "The migration of Muhammad and his followers from Mecca to Medina." },
      theme: "light",
      cast: ["caravan"],
      scene: "A caravan's silhouette crossing the desert toward a glow on the horizon at night; calm dark center.",
    },
    {
      type: "narrative",
      text: "This journey, in the year 622, was so important that it begins the Muslim calendar.",
      pos: "bottom",
      theme: "light",
      era: "622 CE",
      cast: ["crescent-moon", "medina-mosque"],
      scene: "A slender new crescent moon above the rooftops of Medina at deep dusk, a fresh beginning.",
    },
    {
      type: "narrative",
      text: "In Medina he built the first mosque, and a community where neighbors truly cared for one another.",
      pos: "top",
      theme: "dark",
      cast: ["early-mosque-courtyard"],
      scene: "A simple early mosque courtyard with palm-trunk pillars and a low wall at dawn, peaceful and humble.",
    },

    // ───────────────────────── PART SEVEN ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Seven", title: "Among the Prophets" },
      theme: "light",
      cast: ["arabian-desert"],
      scene: "A long range of mountain peaks fading into soft golden mist, many summits in a line.",
    },
    {
      type: "narrative",
      text: "Muhammad taught that he brought no brand-new religion — he carried the same message as the prophets before him.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert"],
      scene: "A long line of distant mountain peaks receding into haze at golden hour, continuity across time.",
    },
    {
      type: "narrative",
      text: "The same God who spoke to Muhammad had also spoken to Adam, Noah, Abraham, Moses, and Jesus.",
      pos: "top",
      theme: "dark",
      cast: ["night-sky"],
      scene: "A chain of soft glowing lights stretched evenly along a dark horizon under stars, a connected lineage.",
    },
    {
      type: "narrative",
      text: "Each prophet told their people the same truth: there is one God, so be good and worship Him alone.",
      pos: "bottom",
      theme: "light",
      cast: ["night-sky"],
      scene: "A single bright star reflected across many separate quiet pools of water in the desert at night.",
    },
    {
      type: "narrative",
      text: "Muslims love and honor every one of these prophets. To insult any of them is not allowed.",
      pos: "top",
      theme: "dark",
      cast: ["oil-lamp"],
      scene: "A row of warm lanterns of equal size glowing along a stone wall at night, each honored the same.",
    },
    {
      type: "narrative",
      text: "Muhammad was the last of them — the final messenger, sent to all people, everywhere, for all time.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert"],
      scene: "Brilliant dawn light reaching across the whole wide earth and sky, the brightest and the last.",
    },

    // ───────────────────────── PART EIGHT ─────────────────────────
    {
      type: "section",
      section: { kicker: "Part Eight", title: "Why He Matters Today" },
      theme: "light",
      cast: ["medina-mosque"],
      scene: "Warm golden light blanketing a peaceful land of hills, palms, and distant homes at sunset.",
    },
    {
      type: "narrative",
      text: "God told Muhammad the very reason he was sent — and the reason was love.",
      pos: "bottom",
      theme: "light",
      cast: ["arabian-desert"],
      scene: "Soft golden light spreading gently across a calm and peaceful land at sunset, warmth everywhere.",
    },
    {
      type: "quote",
      quote: {
        translation: "And We have not sent you except as a mercy to all the worlds.",
        source: "The Prophets · Qur'an 21:107",
        arabic: "وَمَا أَرْسَلْنَاكَ إِلَّا رَحْمَةً لِّلْعَالَمِينَ",
      },
      theme: "light",
      pos: "lower",
      cast: ["arabian-desert", "mecca"],
      scene: "A vast gentle dawn embracing the whole desert and a small sleeping town, soft light reaching into every corner.",
    },
    {
      type: "arabic",
      arabic: { word: "رَحْمَة", translit: "Rahma", meaning: "Mercy — gentleness and compassion. Muhammad was sent as a mercy to all." },
      theme: "light",
      cast: [],
      scene: "A soft warm glow cradling a calm horizon at dawn, tender and embracing; calm dark center.",
    },
    {
      type: "narrative",
      text: "Muslims try to live the way he lived: honest, generous, patient, and kind to every creature.",
      pos: "bottom",
      theme: "light",
      cast: ["dates-and-bread"],
      scene: "A warm evening courtyard where bread is shared and an animal is given water, small acts of love in golden light.",
    },
    {
      type: "narrative",
      text: "When they pray, give to the poor, or smile at a stranger, they are following his example.",
      pos: "top",
      theme: "dark",
      cast: ["early-mosque-courtyard", "people"],
      scene: "Distant faceless figures standing in neat rows of prayer in a courtyard at dawn, seen from behind, calm and unified.",
    },
    {
      type: "narrative",
      text: "His last words to his people urged them to be kind to one another and to never forget God.",
      pos: "bottom",
      theme: "light",
      cast: ["medina-mosque"],
      scene: "A glowing sunset over Medina with the green-domed mosque in silhouette, deep peace.",
    },
    {
      type: "narrative",
      text: "Today more than a billion people across every land love him and try to walk his path.",
      pos: "top",
      theme: "dark",
      cast: ["crescent-moon"],
      scene: "A vast night view of countless lamplit homes spread across hills and a city beneath a crescent moon.",
    },
    {
      type: "narrative",
      text: "And now you know how it began — with one honest man, one quiet cave, and one word: \"Read.\"",
      pos: "bottom",
      theme: "light",
      cast: ["cave-hira"],
      scene: "The cave on the Mountain of Light at dawn, a soft warm glow at its mouth, the whole desert waking below.",
    },
    {
      type: "image",
      cast: ["medina-mosque"],
      scene: "A wordless closing image: the green-domed mosque of Medina in silhouette at dawn, birds rising into a soft gold sky, deep and loving peace.",
    },
  ],
};

export default chapter;
